#!/bin/bash

export CLASSPATH=".:/usr/local/lib/antlr-4.5.2-complete.jar:$CLASSPATH"

INPUT="test/input.txt"
if [[ -n "$2" ]]; then
	INPUT="../$2"
fi

if [[ "$1" == "compile" ]]; then
    cd src/core/grammar
    antlr4 -o ../ -visitor -no-listener -Dlanguage=Python3 TLON.g4
	# java org.antlr.v4.Tool TLON4.g4 -Dlanguage=Python3 -no-listener -visitor
elif [[ "$1" == "clean" ]]; then
	rm src/core/*.class src/core/*.java src/core/*.pyc src/core/TLON*.py src/core/*.tokens
else
	echo "Error: Option '$1' not found"
fi
